version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: laba2_db
      POSTGRES_USER: laba2_user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=laba2_db
      - DJANGO_DB_USER=laba2_user
      - DJANGO_DB_PASSWORD=123

volumes:
  postgres_data:
