# Generated by Django 5.1.7 on 2025-04-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='position',
            field=models.CharField(blank=True, max_length=256, verbose_name='Должность'),
        ),
    ]
