# Generated by Django 5.1.7 on 2025-04-18 16:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=256, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='account_avatars/', verbose_name='Фото')),
                ('position', models.CharField(max_length=256, verbose_name='Должность')),
                ('email', models.CharField(max_length=256, verbose_name='Email')),
                ('phone', models.CharField(max_length=256, verbose_name='Телефон')),
            ],
        ),
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=256, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='account_avatars/', verbose_name='Фото')),
                ('position', models.CharField(max_length=256, verbose_name='Должность')),
                ('email', models.CharField(max_length=256, verbose_name='Email')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='user',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='end_date',
            new_name='deadline',
        ),
        migrations.RemoveField(
            model_name='project',
            name='name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.RemoveField(
            model_name='task',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='project',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(to='web.task', verbose_name='Задачи'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='Без названия', max_length=256, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(default='', max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='', max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, 'High'), (2, 'Medium'), (1, 'Low')], default=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='Без названия', max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='employees',
            field=models.ManyToManyField(to='web.employeeaccount', verbose_name='Работники'),
        ),
        migrations.AddField(
            model_name='task',
            name='employees',
            field=models.ManyToManyField(to='web.employeeaccount', verbose_name='Работники'),
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='web.manageraccount', verbose_name='Менеджер'),
        ),
        migrations.CreateModel(
            name='TaskLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_task_take', models.DateTimeField()),
                ('date_task_close', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, to='web.tasktag', verbose_name='Теги'),
        ),
        migrations.DeleteModel(
            name='Assignment',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='TaskLog',
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
    ]
