# Generated by Django 5.2 on 2025-04-12 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_timeslot_image_timeslottag_timeslot_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='time_slots/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_realtime',
            field=models.BooleanField(default=False, verbose_name='В реально времени'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_date',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='tags',
            field=models.ManyToManyField(to='web.timeslottag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='timeslottag',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timeslottag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
