# Generated by Django 5.1.7 on 2025-04-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_employeeaccount_manageraccount_remove_employee_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='', max_length=512, verbose_name='Описание'),
        ),
    ]
