# Generated by Django 5.1.7 on 2025-05-02 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_customuser_position'),
        ('web', '0003_feedback'),
    ]

    operations = [
    ]
