# Generated by Django 5.2 on 2025-04-12 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_timeslot_end_date_alter_timeslot_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время начала'),
        ),
    ]
