# Generated by Django 5.1.7 on 2025-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='Email'),
        ),
    ]
