# Generated by Django 5.1.7 on 2025-06-06 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_merge_0002_alter_customuser_position_0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
