# Generated by Django 5.2 on 2025-04-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_manageraccount_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/account_avatars/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='manageraccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/account_avatars/', verbose_name='Фото'),
        ),
    ]
