# Generated by Django 5.1.7 on 2025-04-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedBack',
        ),
    ]
